## Here is an explanation of all the data categories found in bootstrap-static (General Data):

# elements
Master list of all the datsets. 88 total

# element_stats
Focuses on player stats from the 'elements' master list

# element_types
Player position-specific. Contains codes, descriptions, and other data related to broad positional items (max on field at once, mi of field at once, etc)

# events
specific fantasy league data relating to that week's games, wrt running the league (rg-deadlines for submissions, if it's the current week, best score, etc.)

# game_settings
Sets the rules & configurations that govern how the league operates in season

# phases
Info about the season's phases (eg each month, first/last Gameweeks, etc.)

# teams
Detailed info about EPL team performance during the season (not the fantasy teams). Lots of statistical categories

# total_players
Absolute sum of the total players in the fantasy.premierleague league:  10,064,327

Endpoint	                                Description
/api/bootstrap-static/	                    General data (players, teams, gameweeks)
/api/element-summary/{element_id}/	        Individual player data (stats, fixtures)
/api/fixtures/	                            All Premier League fixtures
/api/event/{event_id}/live/	                Live gameweek data
/api/events/	                            Gameweek information (deadlines, averages)
/api/teams/	                                Information about Premier League teams
/api/dream-team/{gameweek}/	                Dream team for a specific gameweek
/api/leagues-classic/{league_id}/standings/	Classic league standings
/api/leagues-h2h/{league_id}/standings/	    H2H league standings
/api/entry/{team_id}/	                    Manager’s team details
/api/entry/{team_id}/event/{event_id}/picks/ Manager’s picks for a specific gameweek
/api/entry/{team_id}/transfers/	            Manager’s transfer history
/api/stats/elements/	                    Player ownership and stats

In [1]:
import pandas as pd
import numpy as np
import requests
from sklearn.model_selection import train_test_split

In [2]:
url = "https://fantasy.premierleague.com/api/bootstrap-static/"

In [3]:
request = requests.get(url)
json = request.json()
json.keys()

dict_keys(['events', 'game_settings', 'phases', 'teams', 'total_players', 'elements', 'element_stats', 'element_types'])

In [4]:
print(request)

<Response [200]>

In [5]:
#Create & save as a csv a master list of all EPL players
master_player_df = pd.DataFrame(json['elements'])
master_player_df
#Ensure we can read the whole dataframe, without "..."
pd.set_option("display.max_rows", None)
master_player_df.shape

(655, 88)

In [7]:
pd.set_option("display.max_columns", None)
master_player_df.head()

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,id,in_dreamteam,news,news_added,now_cost,photo,points_per_game,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,expected_goals_per_90,saves_per_90,expected_assists_per_90,expected_goal_involvements_per_90,expected_goals_conceded_per_90,goals_conceded_per_90,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90
0,0.0,0.0,438098,0,0,-1,1,0,3,0.0,0.0,0,Fábio,0.0,1,False,Has joined Portuguese side FC Porto on loan fo...,2024-08-29T11:06:25.241953Z,54,438098.jpg,0.0,Ferreira Vieira,0.0,False,None,u,1,3,0,439,0,2013,505,0.0,0.0,Fábio Vieira,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0.00,0.00,0.00,0.00,628,284,627,286,617,280,631,287,NaN,,NaN,,4.0,,0.00,0.0,0.00,0.00,0.00,0.00,169,106,627,286,627,286,589,257,0.0,0.00
1,0.0,0.0,205651,0,0,-2,2,0,4,0.0,0.0,0,Gabriel,0.0,2,False,Groin Injury - Expected back 15 Sep,2024-08-25T11:00:05.312580Z,68,205651.jpg,0.0,Fernando de Jesus,0.9,False,None,i,1,3,0,15695,287,159289,17323,0.0,0.0,G.Jesus,5,0,0,0,0,0,0,0,1,0,0,0,1,0.2,0.8,0.0,0.1,0,0.00,0.00,0.00,0.15,360,36,315,34,649,69,366,36,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,2.70,0.00,38,17,648,69,648,69,197,33,0.0,0.00
2,NaN,NaN,226597,0,0,0,0,0,2,5.7,5.7,2,Gabriel,4.7,3,False,,None,60,226597.jpg,4.7,dos Santos Magalhães,12.6,False,None,a,1,3,14,151605,28203,216812,69079,0.8,2.3,Gabriel,270,0,0,2,1,0,0,0,1,0,0,1,64,56.0,24.1,17.0,9.7,3,0.24,0.05,0.29,3.58,82,28,136,33,144,28,117,25,NaN,,NaN,,NaN,,0.08,0.0,0.02,0.10,1.19,0.33,82,5,43,8,47,9,32,11,1.0,0.67
3,NaN,NaN,219847,0,0,1,-1,1,4,8.3,8.3,8,Kai,7.3,4,False,,None,81,219847.jpg,7.3,Havertz,17.9,False,None,a,1,3,22,799442,140701,428163,118689,0.9,2.7,Havertz,270,2,1,2,1,0,0,0,0,0,0,5,80,101.8,55.0,91.0,24.7,3,1.43,0.12,1.55,3.58,14,3,48,2,18,8,20,5,NaN,,NaN,,3.0,,0.48,0.0,0.04,0.52,1.19,0.33,12,4,9,3,9,3,17,5,1.0,0.67
4,0.0,0.0,463748,0,0,0,0,0,1,0.0,0.0,0,Karl,0.0,5,False,Loaned to Real Valladolid,2024-08-14T08:31:46.556082Z,40,463748.jpg,0.0,Hein,0.1,False,None,u,1,3,0,0,0,2198,262,0.0,0.0,Hein,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0.00,0.00,0.00,0.00,406,50,390,28,338,25,412,50,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,625,64,411,50,411,50,520,64,0.0,0.00

In [8]:
#what are the element_stats?
stats_player_df = pd.DataFrame(json['element_stats'])
stats_player_df
#Ensure we can read the whole dataframe, without "..."
pd.set_option("display.max_rows", None)
stats_player_df

                         label                        name
0               Minutes played                     minutes
1                 Goals scored                goals_scored
2                      Assists                     assists
3                 Clean sheets                clean_sheets
4               Goals conceded              goals_conceded
5                    Own goals                   own_goals
6              Penalties saved             penalties_saved
7             Penalties missed            penalties_missed
8                 Yellow cards                yellow_cards
9                    Red cards                   red_cards
10                       Saves                       saves
11                       Bonus                       bonus
12         Bonus Points System                         bps
13                   Influence                   influence
14                  Creativity                  creativity
15                      Threat                      threat
16                   ICT Index                   ict_index
17             Game(s) Started                      starts
18              Expected Goals              expected_goals
19            Expected Assists            expected_assists
20  Expected Goal Involvements  expected_goal_involvements
21     Expected Goals Conceded     expected_goals_conceded

In [9]:
#what are the element_types?
types_player_df = pd.DataFrame(json['element_types'])
types_player_df
#Ensure we can read the whole dataframe, without "..."
pd.set_option("display.max_rows", None)
types_player_df.columns

Index(['id', 'plural_name', 'plural_name_short', 'singular_name',
       'singular_name_short', 'squad_select', 'squad_min_select',
       'squad_max_select', 'squad_min_play', 'squad_max_play',
       'ui_shirt_specific', 'sub_positions_locked', 'element_count'],
      dtype='object')

In [10]:
#what are the events?
events_df = pd.DataFrame(json['events'])
events_df
#Ensure we can read the whole dataframe, without "..."
pd.set_option("display.max_rows", None)
events_df.columns

Index(['id', 'name', 'deadline_time', 'release_time', 'average_entry_score',
       'finished', 'data_checked', 'highest_scoring_entry',
       'deadline_time_epoch', 'deadline_time_game_offset', 'highest_score',
       'is_previous', 'is_current', 'is_next', 'cup_leagues_created',
       'h2h_ko_matches_created', 'ranked_count', 'chip_plays', 'most_selected',
       'most_transferred_in', 'top_element', 'top_element_info',
       'transfers_made', 'most_captained', 'most_vice_captained'],
      dtype='object')

In [11]:
#what are the game_settings?
game_settings_df = pd.DataFrame([json['game_settings']])
game_settings_df
#Ensure we can read the whole dataframe, without "..."
pd.set_option("display.max_rows", None)
game_settings_df.columns

Index(['league_join_private_max', 'league_join_public_max',
       'league_max_size_public_classic', 'league_max_size_public_h2h',
       'league_max_size_private_h2h', 'league_max_ko_rounds_private_h2h',
       'league_prefix_public', 'league_points_h2h_win',
       'league_points_h2h_lose', 'league_points_h2h_draw',
       'league_ko_first_instead_of_random', 'cup_start_event_id',
       'cup_stop_event_id', 'cup_qualifying_method', 'cup_type',
       'featured_entries', 'percentile_ranks', 'squad_squadplay',
       'squad_squadsize', 'squad_team_limit', 'squad_total_spend',
       'ui_currency_multiplier', 'ui_use_special_shirts',
       'ui_special_shirt_exclusions', 'stats_form_days',
       'sys_vice_captain_enabled', 'transfers_cap', 'transfers_sell_on_fee',
       'max_extra_free_transfers', 'league_h2h_tiebreak_stats', 'timezone'],
      dtype='object')

In [12]:
#what are the phases?
phases_df = pd.DataFrame(json['phases'])
phases_df
#Ensure we can read the whole dataframe, without "..."
pd.set_option("display.max_rows", None)
phases_df

    id       name  start_event  stop_event  highest_score
0    1    Overall            1          38          309.0
1    2     August            1           3          309.0
2    3  September            4           6            NaN
3    4    October            7           9            NaN
4    5   November           10          13            NaN
5    6   December           14          19            NaN
6    7    January           20          23            NaN
7    8   February           24          27            NaN
8    9      March           28          29            NaN
9   10      April           30          34            NaN
10  11        May           35          38            NaN

In [13]:
#what are the teams?
teams_df = pd.DataFrame(json['teams'])
teams_df
#Ensure we can read the whole dataframe, without "..."
pd.set_option("display.max_rows", None)
teams_df

,code,draw,form,id,loss,name,played,points,position,short_name,strength,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,0,ARS,5,None,False,0,1350,1380,1370,1370,1330,1390,1
1,7,0,None,2,0,Aston Villa,0,0,0,AVL,3,None,False,0,1120,1245,1110,1140,1130,1350,2
2,91,0,None,3,0,Bournemouth,0,0,0,BOU,3,None,False,0,1100,1100,1075,1100,1130,1105,127
3,94,0,None,4,0,Brentford,0,0,0,BRE,3,None,False,0,1100,1100,1105,1095,1100,1110,130
4,36,0,None,5,0,Brighton,0,0,0,BHA,3,None,False,0,1100,1100,1100,1105,1100,1100,131
5,8,0,None,6,0,Chelsea,0,0,0,CHE,3,None,False,0,1130,1255,1090,1180,1170,1330,4
6,31,0,None,7,0,Crystal Palace,0,0,0,CRY,3,None,False,0,1100,1165,1110,1180,1090,1155,6
7,11,0,None,8,0,Everton,0,0,0,EVE,3,None,False,0,1090,1125,1100,1175,1080,1080,7
8,54,0,None,9,0,Fulham,0,0,0,FUL,3,None,False,0,1080,1125,1070,1130,1090,1120,34
9,40,0,None,10,0,Ipswich,0,0,0,IPS,2,None,False,0,1050,1050,1050,1050,1050,1050,8
10,13,0,None,11,0,Leicester,0,0,0,LEI,2,None,False,0,1050,1060,1060,1050,1060,1050,26
11,14,0,None,12,0,Liverpool,0,0,0,LIV,4,None,False,0,1235,1370,1170,1350,1300,1390,10
12,43,0,None,13,0,Man City,0,0,0,MCI,5,None,False,0,1355,1380,1335,1370,1375,1390,11
13,1,0,None,14,0,Man Utd,0,0,0,MUN,3,None,False,0,1115,1175,1110,1120,1120,1230,12
14,4,0,None,15,0,Newcastle,0,0,0,NEW,4,None,False,0,1130,1285,1100,1185,1160,1380,23
15,17,0,None,16,0,Nott'm Forest,0,0,0,NFO,3,None,False,0,1090,1100,1085,1115,1090,1090,15
16,20,0,None,17,0,Southampton,0,0,0,SOU,2,None,False,0,1050,1050,1050,1050,1050,1050,20
17,6,0,None,18,0,Spurs,0,0,0,TOT,3,None,False,0,1165,1225,1100,1125,1230,1330,21
18,21,0,None,19,0,West Ham,0,0,0,WHU,3,None,False,0,1095,1100,1060,1100,1130,1105,25
19,39,0,None,20,0,Wolves,0,0,0,WOL,3,None,False,0,1095,1100,1075,1105,1115,1100,38

In [14]:
#what are the total_players?
total_players = json['total_players']

print(f"Total players = {total_players}")

Total players = 10064327