In [1]:
import pandas as pd

In [2]:
fpl_goalkeepers = pd.read_csv('../data/processed/goalie_final_merge.csv')
sorare_goalkeepers = pd.read_csv('../sorare/sorare_data/predictions/sorare_goalkeepers_predictions.csv')

print(fpl_goalkeepers.columns)
print(sorare_goalkeepers.columns)

fpl_goalkeepers = fpl_goalkeepers.rename(columns={'first_name': 'First_Name', 'second_name': 'Last_Name', 'Predicted_Total_Points':'Predicted_Points'}).reset_index()
fpl_goalkeepers_filtered = fpl_goalkeepers[['id','First_Name','Last_Name', 'Predicted_Points']]

sorare_goalkeepers_filtered = sorare_goalkeepers[['First_Name','Last_Name', 'So_5_Scores_9', 'sorare_predictions']]

print(fpl_goalkeepers.shape)
print(sorare_goalkeepers.shape)

print("------------------------")

print(fpl_goalkeepers_filtered.shape)
print(sorare_goalkeepers_filtered.shape)

Index(['Unnamed: 0', 'id', 'season', 'first_name', 'second_name',
       'Predicted_Total_Points'],
      dtype='object')
Index(['Display_Name', 'First_Name', 'Last_Name', 'Player_Number', 'Position',
       'Current_Club', 'So_5_Scores_9', 'sorare_xgb_predictions',
       'sorare_lgbm_predictions', 'sorare_elastic_predictions',
       'sorare_predictions'],
      dtype='object')
(33, 7)
(56, 11)
------------------------
(33, 4)
(56, 4)

In [3]:
goalkeepers = pd.merge(sorare_goalkeepers_filtered, fpl_goalkeepers_filtered, on=['First_Name', 'Last_Name'] )

print(goalkeepers.shape)

goalkeepers['Weighted_BOR3_Score'] = (goalkeepers['sorare_predictions'] * 0.75) + (goalkeepers['Predicted_Points'] * 0.25)

(22, 6)

In [4]:
goalkeepers = goalkeepers.sort_values('Weighted_BOR3_Score', ascending=False)

goalkeepers.to_csv('../data/predictions/weighted_bor3_goalkeepers.csv')
goalkeepers

,First_Name,Last_Name,So_5_Scores_9,sorare_predictions,id,Predicted_Points,Weighted_BOR3_Score
9,Jordan,Pickford,59.396193,58.521471,235,78.784,63.587103
2,Bart,Verbruggen,70.000000,60.279516,146,36.995,54.458387
3,Bernd,Leno,55.200000,40.341718,248,68.581,47.401538
7,Guglielmo,Vicario,76.100000,36.826706,508,59.482,42.490529
21,Łukasz,Fabiański,60.700000,49.642520,521,13.549,40.619140
12,Martin,Dúbravka,0.000000,40.699215,396,37.819,39.979161
1,André,Onana,30.700000,30.500747,383,66.961,39.615810
11,Mark,Travers,74.960000,38.619995,84,9.212,31.267996
18,Robin,Olsen,8.200000,27.911504,51,10.974,23.677128
8,Jason,Steele,0.000000,17.908856,142,22.393,19.029892
10,Mark,Flekken,0.000000,4.813786,91,60.336,18.694340
13,Matt,Turner,0.000000,13.689648,445,21.667,15.683986
15,Nick,Pope,0.000000,8.344122,413,29.030,13.515591
6,Dean,Henderson,0.000000,4.459257,201,25.233,9.652693
19,Sam,Johnstone,0.000000,1.465988,204,33.022,9.354991
17,Robert,Sánchez,0.000000,2.387842,185,29.032,9.048881
14,Matz,Sels,0.000000,3.530450,443,18.899,7.372587
20,Stefan,Ortega Moreno,0.000000,3.457298,358,10.953,5.331224
4,Caoimhin,Kelleher,0.000000,1.192234,325,17.586,5.290675
0,Aaron,Ramsdale,0.000000,1.354948,14,10.431,3.623961
5,Daniel,Bentley,0.000000,1.546278,536,8.039,3.169458
16,Remi,Matthews,0.000000,0.393457,209,1.033,0.553342